'Featured Image':
    meta:
        rule: featured_image
    options:
        max-size: 300
        format: jpg
        dimensions:
        width: 760
        height: 350

'Excerpt':
    meta:
        rule: excerpt
    options:
        min-length: 30
        max-length: 300

'Scheduled':
    meta:
        rule: scheduled
    options:
        publish-time: '15:00'

'Categories':
    meta:
        rule: categories
    options:
        not:
            - Uncategorized
        not-only:
            - Featured
        not-primary:
            - Featured

'Links':
    meta:
        rule: links
    options:
        internal:
            open-in-new-tab: false
        external:
            open-in-new-tab: true

'Images':
    meta:
        rule: images
